# Site
repository: lmsimp/lmsimp.github.io

# Content configuration version
version: 2

# Personal info
name: Lisa Breckels (Simpson)
title: Research Associate and Computational Biologist
email: lms79@cam.ac.uk
website: http://lmsimp.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: lmsimp
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: https://uk.linkedin.com/in/lisa-breckels-née-simpson-41026087
# xing_username: jekyll
# pinterest_username: jekyll
orcid_username: 0000-0001-8918-7171

# Additional icon links
additional_links:
- title: https://proteomics.bio.cam.ac.uk/research-team
  icon: fas fa-globe
  url: https://proteomics.bio.cam.ac.uk/research-team
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Computational Biologist located at the [Cambridge Centre for Proteomics (CCP)](https://proteomics.bio.cam.ac.uk), University of Cambridge, UK. [My main area of research](https://scholar.google.co.uk/citations?user=SJoJ3n0AAAAJ&hl=en) focuses on computational analysis of high-throughput quantitative spatial proteomics data and development of new machine learning tools and R packages.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Bioconductor Contributions
        # link: github.com/lmsimp
        # link_text: Project Website
        additional_links:
          - title:  github.com/lmsimp
            icon: fab fa-github
            url: github.com/lmsimp
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #  Some quote info here
        
        #content: 
        
        #- layout: left
        #sub_title: <mark>bandle</mark>
        #description: The [bandle](https://bioconductor.org/packages/devel/bioc/html/bandle.html) is an R package for 
        #  the Bayesian analysis of differential subcellular localisation experiments.
        #  
        #- layout: left
        #sub_title: <mark>pRoloc</mark>
        #description: [pRoloc](https://bioconductor.org/packages/release/bioc/html/pRoloc.html) implements machine learning and visualisation methods for the analysis and interogation of quantitiative mass spectrometry data to reliably infer protein sub-cellular localisation.
        
        description: | # this will include new lines to allow paragraphs
          The <mark>bandle</mark> package: [bandle](https://bioconductor.org/packages/devel/bioc/html/bandle.html) is an R package for 
          the Bayesian analysis of differential subcellular localisation experiments.
          
          The <mark>pRoloc</mark> package: [pRoloc](https://bioconductor.org/packages/release/bioc/html/pRoloc.html) implements machine learning and visualisation methods for the analysis and interogation of quantitiative mass spectrometry data to reliably infer protein sub-cellular localisation.
         
          The <mark>pRolocGUI</mark> package: [pRolocGUI](https://bioconductor.org/packages/release/bioc/html/pRolocGUI.html) comprises functions to interactively visualise organelle (spatial) proteomics data on the basis of pRoloc, pRolocdata and [shiny](https://shiny.rstudio.com).
          
          The <mark>pRolocdata</mark> package: [pRolocdata](https://bioconductor.org/packages/release/data/experiment/html/pRolocdata.html) is a data package containing mass-spectrometry based spatial proteomics data sets and protein complex separation data. 

          
          
          
      - layout: top-middle
        title: Spatial Proteomics at CCP
        # link: github.com/lmsimp
        # link_text: Project Website
        additional_links:
          - title: 
            # icon: fab fa-github
            # url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #  This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I am involved in many collaborations within the Lilley Lab and work closely with wet lab biologists on downstream data analysis of proteomics data, generated from different technologies and cell lines.

   
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Cambridge
        sub_title: Computational Biologist
        link: Cambridge Centre for Proteomics, University of Cambridge, UK
        link_text: https://proteomics.bio.cam.ac.uk
        caption: November 2010 - Present
        description:
           I am a Postdoctoral Research Associate in [Professor Kathryn Lilley]( https://proteomics.bio.cam.ac.uk) group located in Cambridge Centre for Proteomics at the University of Cambridge. My research focuses on R package development and the computational analysis of high-throughput quantitative spatial proteomics data. This includes the application and development of new machine learning tools. Our work is contributed to the R Bioconductor project in the form of dedicated software packages (see projects) pioneered by [Prof Laurent Gatto](https://lgatto.github.io/about) at UCLouvain, Belgium. 
           
      - layout: left
        title: University of Cambridge
        sub_title: Undergraduate Mathematics Supervisor
        caption: November 2010 - July 2011
        description:
           Elementary Mathematics supervisor for Wolfson College and Newnham College at the University of Cambridge.

      - layout: left
        title: GlaxoSmithKline (GSK)
        sub_title: Industrial CASE Student
        caption: October 2006 - May 2010
        description:
           CASE (Collaborative Awards in Science and Engineering) PhD studentship with GSK (Harlow, UK) working in the Computational Chemistry Division in R&D, under the supervision of Dr Ian Wall and Dr Frank Blaney. My main research focused on using molecular modelling and molecular dynamics simulation techniques to gain an insight into the structural and functional properties of GPCRs in their multiple states.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
    
      - layout: left
        title: University of Essex 
        caption: 2006 - 2010
        sub_title: PhD Computational Chemistry/Biology
        description: 
              Funded BBSRC CASE (Collaborative Awards in Science and Engineering) Award project under the supervision of Prof. Chris Reynolds (Dept. of Biological Sciences, University of Essex) and Dr. Ian Wall (GSK, Harlow). My main research focused on structure-based drug-design in which I used molecular modelling and molecular dynamics simulation techniques to gain an insight into the structural and functional properties of GPCRs in their multiple states.
              
      - layout: left
        title: University of Essex
        caption: 2003-2006
        sub_title: BSc (Hons) Mathematics (1st Class)

- layout: left
        title: Publications
        caption: 2006 - Present
        description:

Eneko Villanueva, Tom Smith, Mariavittoria Pizzinga, Mohamed Elzek, Rayner ML Queiroz, Robert F Harvey, Lisa M Breckels, Oliver M Crook, Mie Monti, Veronica Dezi, Anne E Willis, Kathryn S Lilley. *A system-wide quantitative map of RNA and protein subcellular localisation dynamics* bioRxiv 2022 DOI:[10.1101/2022.01.24.477541](https://doi.org/10.1101/2022.01.24.477541)


Oliver M. Crook, Colin T. R. Davies, Lisa M. Breckels, Josie A. Christopher, Laurent Gatto, Paul D.W. Kirk, Kathryn S. Lilley. *Inferring differential subcellular localisation in comparative spatial proteomics using BANDLE* 2021 bioRxiv DOI:[2021.01.04.425239](https://doi.org/10.1101/2021.01.04.425239)

Mulvey CM, Breckels LM, Crook O, Sanders D, Ribeiro A, Geladaki A,
Christoforou A, Britovsek NK, Hurrell T, Deery MJ, Gatto L, Smith A,
and Lilley KS. *Spatiotemporal proteomic profiling of the
pro-inflammatory response to lipopolysaccharide in the THP-1 human
leukaemia cell line* Nat Commun 12, 5773
(2021). DOI:[10.1038/s41467-021-26000-9](https://doi.org/10.1038/s41467-021-26000-9)


Baers LL, Breckels LM, Mills LA, Gatto L, Deery M, Stevens TJ, Howe
CH, Lilley KS, Lea-Smith DJ *Proteome mapping of a cyanobacterium
reveals distinct compartment organisation and cell-dispersed
metabolism*, Plant Physiology 2019
[https://doi.org/10.1104/pp.19.00897](https://doi.org/10.1104/pp.19.00897).

Laurent Gatto, Lisa M Breckels, Kathryn S Lilley *Assessing
sub-cellular resolution in spatial proteomics experiments* Current
Opinion in Chemical Biology, 48 123-149
(2019) DOI:[10.1016/j.cbpa.2018.11.015](https://doi.org/10.1016/j.cbpa.2018.11.015).

Aikaterini Geladaki, Nina Kocevar Britovsek, Lisa M. Breckels, Tom
S. Smith, Claire M. Mulvey, Oliver M. Crook, Laurent Gatto, Kathryn
S. Lilley [*Combining LOPIT with differential ultracentrifugation for
high-resolution spatial
proteomics*](https://www.nature.com/articles/s41467-018-08191-w)
Nature Communications volume 10, Article number:331 (2019) (pre-print
[10.1101/378364](https://doi.org/10.1101/378364)).

Thul PJ, *et al.* *A subcellular map of the human
proteome*. Science. 2017 May 11. pii:
eaal3321. [doi:10.1126/science.aal3321](http://science.sciencemag.org/content/early/2017/05/10/science.aal3321). [Epub ahead of print]
PubMed [PMID:28495876](https://www.ncbi.nlm.nih.gov/pubmed/28495876).

Mulvey CM, Breckels LM, Geladaki A, Kocevar Britovsek N, Nightingale
DJH, Christoforou A , Elzek M, Deery MJ, Gatto L, Lilley KS. *Using
HyperLOPIT to perform high-resolution mapping of the spatial
proteome*. Nature Protocols, 12, 1110–1135 (2017)
[doi:10.1038/nprot.2017.026](https://www.nature.com/nprot/journal/v12/n6/full/nprot.2017.026.html)
(See the
[F1000Research workflow](https://f1000research.com/articles/5-2926/)
for details on the computational side of the protocol.)

Breckels LM, Mulvey CM, Lilley KS and Gatto L. *A Bioconductor
workflow for processing and analysing spatial proteomics
data* F1000Research 2016, 5:2926
([doi:10.12688/f1000research.10411.1](https://f1000research.com/articles/5-2926/)).
[Software: [MSnbase](http://bioconductor.org/packages/MSnbase),
[pRoloc](http://bioconductor.org/packages/pRoloc),
[pRolocGUI](http://bioconductor.org/packages/pRolocGUI)]

Breckels LM, Holden S, Wonjar D, Mulvey CM, Christoforou A, Groen AJ,
Kohlbacher O, Lilley KS, Gatto L. *Learning from heterogeneous data
sources: an application in spatial proteomics*. PLoS Comput Biol. 2016
May 13;12(5):e1004920
[doi:10.1371/journal.pcbi.1004920](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004920),
[Software](http://bioconductor.org/packages/release/bioc/html/pRoloc.html))

Christoforou A, Mulvey CM, Breckels LM, Geladaki A, Hurrell T, Hayward
PC, Naake T, Gatto L, Viner R, Arias AM, Lilley KS. A draft map of the
mouse pluripotent stem cell spatial proteome. Nat Commun. 2016 Jan
12;7:9992
[doi:10.1038/ncomms9992](http://www.nature.com/ncomms/2016/160112/ncomms9992/abs/ncomms9992.html)
([PMID:26754106](http://www.ncbi.nlm.nih.gov/pubmed/26754106),
[data](http://www.bioconductor.org/packages/release/data/experiment/html/pRolocdata.html),
[PRIDE](http://www.ebi.ac.uk/pride/archive/projects/PXD001279),
[resource](https://lgatto.shinyapps.io/christoforou2015/))

Gatto L, Breckels LM, Naake T and Gibb S *Visualisation of proteomics
data using R and Bioconductor*. Proteomics. 2015
Feb 18. doi:10.1002/pmic.201400392
([PubMed](http://www.ncbi.nlm.nih.gov/pubmed/25690415),
[Publisher](http://onlinelibrary.wiley.com/doi/10.1002/pmic.201400392/abstract)
and software:
[Bioconductor](http://bioconductor.org/packages/devel/data/experiment/html/RforProteomics.html),
[github](https://github.com/lgatto/RforProteomics)).

Tomizioli M, <i>et al.</i> *Deciphering thylakoid sub-compartments
using a mass spectrometry-based approach*, Mol Cell Proteomics. 2014
May 28. (<a
href="http://mcponline.org/content/early/2014/05/28/mcp.M114.040923.abstract">Publisher</a>,
<a href="http://www.ncbi.nlm.nih.gov/pubmed/24872594">PubMed</a>)
Gatto L, <i>et al.</i> *A foundation for reliable spatial proteomics
data analysis*, Mol Cell Proteomics. 2014 Aug;13(8):1937-52. (<a
href="http://www.mcponline.org/content/13/8/1937.long">Publisher</a>,
<a href="http://www.ncbi.nlm.nih.gov/pubmed/24846987">PubMed</a>, <a
href="http://www.bioconductor.org/packages/devel/bioc/html/pRoloc.html">software</a>,
<a
href="http://www.genomeweb.com/proteomics/cambridge-researchers-outline-best-practices-analysis-organelle-proteomics-data">press
coverage</a>)

Gatto L., Breckels L.M, Burger T, Wieczorek S. and Lilley
K.S. *Mass-spectrometry based spatial proteomics data analysis using
pRoloc and pRolocdata*, Bioinformatics, 2014 (<a
href="http://www.bioconductor.org/packages/release/bioc/html/pRoloc.html">software</a>,
<a href="http://www.ncbi.nlm.nih.gov/pubmed/24413670">PubMed</a>,
<a href="http://bioinformatics.oxfordjournals.org/content/30/9/1322">publisher</a>,
<a href="http://www.bioconductor.org/packages/release/bioc/html/pRoloc.html">software</a>
and <a href="http://www.bioconductor.org/packages/release/data/experiment/html/pRolocdata.html">data</a>).

Groen A., Sancho-Andr&eacute;s G., Breckels LM., Gatto L., Aniento
F. and Lilley K.S. *Identification of Trans Golgi Network proteins in
Arabidopsis thaliana root tissue* Journal of Proteome Research, 2013
(<a href="http://www.ncbi.nlm.nih.gov/pubmed/24344820">PubMed</a>, <a
href="http://pubs.acs.org/doi/abs/10.1021/pr4008464">publisher</a>).

Breckels L.M., Gatto L., Christoforou A., Groen A.J., Lilley K.S. and
Trotter M.W.B.  *The Effect of Organelle Discovery upon Sub-Cellular
Protein Localisation*, Journal of Proteomics, 2013 (<a
href="http://www.ncbi.nlm.nih.gov/pubmed/23523639">PubMed</a>,
<a href="http://www.bioconductor.org/packages/release/bioc/html/pRoloc.html">software</a>).

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
